import pytest
import asyncio
from playwright.async_api import async_playwright
import config
from agents.browser_agent import (
    navigate_to_magicbricks,
    select_rent_tab,
    fill_location,
    apply_bhk_filter,
    apply_budget_filter,
    click_search
)

@pytest.mark.asyncio
async def test_ui_filters_are_applied_correctly():
    """
    End-to-End test to verify that the browser agent correctly clicks the UI
    and applies the Rent, Location, BHK, and Budget filters.
    We verify this by checking the final URL after clicking Search.
    """
    # Force test configuration
    config.SEARCH_KEYWORD = "Whitefield"
    config.MIN_BUDGET = 50000
    config.MAX_BUDGET = 60000
    
    async with async_playwright() as p:
        # Launch headless for faster testing
        browser = await p.chromium.launch(
            headless=True,
            args=["--disable-blink-features=AutomationControlled", "--no-sandbox"]
        )
        context = await browser.new_context(user_agent=config.USER_AGENT)
        page = await context.new_page()
        
        try:
            # Execute the UI interactions
            await navigate_to_magicbricks(page)
            await select_rent_tab(page)
            await fill_location(page)
            await apply_bhk_filter(page)
            await apply_budget_filter(page)
            await click_search(page)
            
            # The search button triggers a page navigation to the results page.
            # We check the final URL to prove that MagicBricks registered our UI clicks.
            final_url = page.url.lower()
            print(f"\nFinal URL generated by our clicks: {final_url}")
            
            # Verify MagicBricks registered 'Rent'
            assert "rent" in final_url or "category=r" in final_url, "Rent filter was not applied!"
            
            # Verify MagicBricks registered 'Whitefield'
            assert "whitefield" in final_url, "Location filter was not applied!"
            
            # Verify MagicBricks registered '2 BHK'
            assert "2" in final_url, "BHK filter was not applied!"
            
            # Verify MagicBricks registered the '50000 to 60000' budget
            assert "50000" in final_url, "Min budget was not applied!"
            assert "60000" in final_url, "Max budget was not applied!"

        finally:
            await browser.close()
